version: "3.4"

services:
# ========================
# Alfresco products
# ========================
  alfresco:
    image: "${RICKSOFT_TEST_ACS_REPO_IMAGE}"
    mem_limit: 1900m
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Dencryption.keystore.type=JCEKS
        -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
        -Dencryption.keyAlgorithm=DESede
        -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
        -Dmetadata-keystore.password=mp6yc0UD9e
        -Dmetadata-keystore.aliases=metadata
        -Dmetadata-keystore.metadata.password=oKIWzVdEdA
        -Dmetadata-keystore.metadata.algorithm=DESede
      JAVA_OPTS: >-
        -Ddb.driver=org.postgresql.Driver
        -Ddb.username=ricksoft
        -Ddb.password=ricksoft
        -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
        -Dsolr.host=solr6
        -Dsolr.port=8983
        -Dsolr.secureComms=secret
        -Dsolr.sharedSecret=secret
        -Dsolr.base.url=/solr
        -Dindex.subsystem.name=solr6
        -Dshare.host=127.0.0.1
        -Dshare.port=8080
        -Dalfresco.host=4.189.253.13
        -Dalfresco.port=8080
        -Daos.baseUrlOverwrite=http://4.189.253.13:8080/alfresco/aos
        -Dmessaging.broker.url="failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true"
        -Ddeployment.method=DOCKER_COMPOSE
        -Dtransform.service.enabled=true
        -Dtransform.service.url=http://transform-router:8095
        -Dsfs.url=http://shared-file-store:8099/
        -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
        -Dcsrf.filter.enabled=false
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://4.189.253.13:8080/alfresco/api/-default-/public/alfresco/versions/1/probes/-ready-
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 1m
    volumes:
      - acs-volume:/usr/local/tomcat/alf_data
      - ./server.xml:/usr/local/tomcat/conf/server.xml
  share:
    image: "${RICKSOFT_TEST_ACS_SHARE_IMAGE}"
    mem_limit: 1g
    environment:
      REPO_HOST: "alfresco"
      REPO_PORT: "8080"
      JAVA_OPTS: >-
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
        -Dalfresco.host=4.189.253.13
        -Dalfresco.port=8080
        -Dalfresco.context=alfresco
        -Dalfresco.protocol=http
  transform-router:
    mem_limit: 512m
    image: quay.io/alfresco/alfresco-transform-router:4.1.1
    environment:
      JAVA_OPTS: >-
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
      ACTIVEMQ_URL: nio://activemq:61616
      CORE_AIO_URL: http://transform-core-aio:8090
      FILE_STORE_URL: >-
        http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file
    ports:
      - "8095:8095"
    depends_on:
      - activemq
  transform-core-aio:
    image: alfresco/alfresco-transform-core-aio:5.1.1
    mem_limit: 1536m
    environment:
      JAVA_OPTS: >-
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
      ACTIVEMQ_URL: nio://activemq:61616
      FILE_STORE_URL: >-
        http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file
    ports:
      - "8090:8090"
    depends_on:
      - activemq
  shared-file-store:
    image: quay.io/alfresco/alfresco-shared-file-store:4.1.1
    mem_limit: 512m
    environment:
      JAVA_OPTS: >-
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
      scheduler.content.age.millis: 86400000
      scheduler.cleanup.interval: 86400000
    ports:
      - "8099:8099"
    volumes:
      - shared-file-store-volume:/tmp/Alfresco/sfs
  postgres:
    image: postgres:14.4
    mem_limit: 512m
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
  solr6:
    image: quay.io/alfresco/search-services:2.0.10
    mem_limit: 2g
    environment:
      # Solr needs to know how to register itself with Alfresco
      SOLR_ALFRESCO_HOST: "alfresco"
      SOLR_ALFRESCO_PORT: "8080"
      # Alfresco needs to know how to call solr
      SOLR_SOLR_HOST: "solr6"
      SOLR_SOLR_PORT: "8983"
      # Create the default alfresco and archive cores
      SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
      # HTTPS or SECRET
      ALFRESCO_SECURE_COMMS: "secret"
      # SHARED SECRET VALUE
      JAVA_TOOL_OPTIONS: >-
        -Dalfresco.secureComms.secret=secret
    ports:
      - "8083:8983" # Browser port
    volumes:
      - ass-volume:/opt/alfresco-search-services/contentstore
      - ass-volume:/opt/alfresco-search-services/data
  activemq:
    image: alfresco/alfresco-activemq:5.18-jre17-rockylinux8
    mem_limit: 1g
    ports:
      - "8161:8161" # Web Console
      - "5672:5672" # AMQP
      - "61616:61616" # OpenWire
      - "61613:61613" # STOMP

# ========================
# Atlassian products
# ========================
  jira:
    container_name: jira
    image: atlassian/jira-software:9.12.8
    environment:
      ATL_PROXY_NAME: 4.189.253.13
      ATL_PROXY_PORT: 8080
      ATL_TOMCAT_SCHEME: http
      ATL_TOMCAT_CONTEXTPATH: jira
      ATL_JDBC_URL: jdbc:postgresql://postgres:5432/jira
      ATL_JDBC_USER: ricksoft
      ATL_JDBC_PASSWORD: ricksoft
      ATL_DB_DRIVER: org.postgresql.Driver
      ATL_DB_TYPE: postgres72
      JVM_SUPPORT_RECOMMENDED_ARGS: "-Dupm.plugin.upload.enabled=true"
    volumes:
      - jira-volume:/var/atlassian/application-data/jira
  confluence:
    image: atlassian/confluence:8.5.9
    volumes:
      - confluence-volume:/var/atlassian/application-data/confluence
    environment:
      ATL_PROXY_NAME: 4.189.253.13
      ATL_PROXY_PORT: 8080
      ATL_TOMCAT_SCHEME: http
      ATL_TOMCAT_CONTEXTPATH: wiki
      JVM_SUPPORT_RECOMMENDED_ARGS: "-Dupm.plugin.upload.enabled=true"
      ATL_JDBC_URL: jdbc:postgresql://postgres:5432/confluence
      ATL_JDBC_USER: ricksoft
      ATL_JDBC_PASSWORD: ricksoft
      ATL_DB_TYPE: postgresql
      ATL_DB_DRIVER: org.postgresql.Driver
      ATL_DB_SCHEMA_NAME: public

# ========================
# Other
# ========================
  proxy:
    image: nginx:latest
    mem_limit: 128m
    depends_on:
      - alfresco
      - share
      - jira
      - confluence
    ports:
      - 8080:8080 # default
    links:
      - alfresco
      - share
      - jira
      - confluence
    volumes:
      - ${PWD}/nginx/default.conf:/etc/nginx/conf.d/default.conf
volumes:
  acs-volume:
    external: true
    name: "${RICKSOFT_TEST_ACS_IDENTIFIER}-acs"
  ass-volume:
    external: true
    name: "${RICKSOFT_TEST_ACS_IDENTIFIER}-ass"
  db-volume:
    external: true
    name: "${RICKSOFT_TEST_ACS_IDENTIFIER}-db"
  jira-volume:
    external: true
    name: "${RICKSOFT_TEST_ACS_IDENTIFIER}-jira"
  confluence-volume:
    external: true
    name: "${RICKSOFT_TEST_ACS_IDENTIFIER}-confluence"
  shared-file-store-volume:
    driver_opts:
      type: tmpfs
      device: tmpfs
